stages:
  obter_dados:
    cmd: python -m src.data.get_data dvc-fiap-mlops dataset/laptopPrice.csv data/raw/laptopPrice.csv
    deps:
    - src/data/get_data.py
    outs:
    - data/raw/laptopPrice.csv

  processar_dados:
    cmd: python -m src.data.make_dataset data/raw/laptopPrice.csv data/processed/laptopPrice.csv
    deps:
    - src/data/make_dataset.py
    - data/raw/laptopPrice.csv
    outs:
    - data/processed/laptopPrice.csv

  processar_features:
    cmd: python -m src.data.make_features data/processed/laptopPrice.csv data/processed/laptopPrice-features.csv
    deps:
    - src/data/make_features.py
    - data/processed/laptopPrice.csv
    outs:
    - data/processed/laptopPrice-features.csv

  treinamento:
    cmd: python -m src.models.train_model data/processed/laptopPrice-features.csv
      models/model.pkl
    deps:
    - src/models/train_model.py
    - data/processed/laptopPrice-features.csv
    outs:
    - models/model.pkl
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
artifacts:
  laptop-pricing:
    path: models/model.pkl
    type: model
    desc: Modelo de predição de preço de laptop
    labels:
    - regressão
